[dagster-dbt] Fix runtime selection args for op usage (#24341)
## Summary & Motivation

Re-injection was handled only for assets but not for ops, which caused:

```
FAILED dagster_cloud_dagit_tests/dagster_insights_tests/test_dagster_insights_e2e.py::test_e2e_cloud[snowflake_metrics_job-dbt_job_info1] - dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command
`dbt build --profile unittest`
failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /workspace/build/buildkite/dagster-cloud/python_modules/dagster-cloud-dagit/dagster_cloud_dagit_tests/dagster_insights_tests/dbt_project/target/my_custom_dbt_run_op-9dc0478-da89f9d/dbt.log.
Errors parsed from dbt logs:
15 of 29 ERROR creating sql table model main.orders_partitioned ................ [ERROR in 0.01s]
  Compilation Error in model orders_partitioned (models/orders_partitioned.sql)
  Required var 'min_date' not found in config:
  Vars supplied to orders_partitioned = {}
FAILED dagster_cloud_dagit_tests/dagster_insights_tests/test_dagster_insights_e2e.py::test_e2e_cloud[snowflake_metrics_job_s3_only-dbt_job_info1] - dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command
`dbt build --profile unittest`
failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /workspace/build/buildkite/dagster-cloud/python_modules/dagster-cloud-dagit/dagster_cloud_dagit_tests/dagster_insights_tests/dbt_project/target/my_custom_dbt_run_op-7caf6c9-7d77510/dbt.log.
Errors parsed from dbt logs:
15 of 29 ERROR creating sql table model main.orders_partitioned ................ [ERROR in 0.01s]
  Compilation Error in model orders_partitioned (models/orders_partitioned.sql)
  Required var 'min_date' not found in config:
  Vars supplied to orders_partitioned = {}
```

## Test Plan

BK

Internal-RevId: a6dca77e245b7423a75567a9d7285e63850b54ca