Support special chars in username and passwords for registry login (#22449)
## Summary & Motivation

Shell interpolation breaks special chars like `$` in usernames and
passwords. The new serverless registry (goharbor.io) uses robot accounts
with `$` in the username.

This removes `shell=True` to avoid all shell interpolation and directly
passes the password to stdin.

## Test Plan

ran locally, verified it works.

```bash

> uv run dg plus deploy --organization=shalabh-test-k8s-hjg48jg84 --deployment=prod --agent-type=serverless --python-version=3.10 --target-path=/Users/shalabh/src/shalabh_test_k8s_hjg
...
                                                                                  0.0s
 => => naming to registry.dogfood.dagster.plus/tenant-shalabh-test-k8s-hjg48jg84-0ba9f6cf:prod-shalabh_test_k8s_hjg-819fb0a0c0424c0c9be272f0ae487782                                    0.0s
Login Succeeded
The push refers to repository [registry.dogfood.dagster.plus/tenant-shalabh-test-k8s-hjg48jg84-0ba9f6cf]
...
```

Previously login failed
[with](https://github.com/shalabh-dagster-lab/shalabh_test_k8s_hjg/actions/runs/24064794416/job/70452639235#step:11:377):

```
4
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo 3wHiLQ0OGFyH9iGCcycJ3ZDhJSvxdDk9 | docker login --username robot$tenant-shalabh-test-k8s-hjg48jg84-0ba9f6cf+push-shalabh-test-k8s-hjg48jg84-0ba9f6cf --password-stdin registry.dogfood.dagster.plus/tenant-shalabh-test-k8s-hjg48jg84-0ba9f6cf' returned non-zero exit status 1.

```

Internal-RevId: f6dd8f972d6a6cc612dca1c5a65c1cb330effd50